---
# version: 1.0.{build}-{branch}

environment:
  LOG_SPEC_ORDER: true
  matrix:
    # FIXME: enable ruby 2.5 on windows once puppet and puppet-module gems have unpinned ffi
    # - RUBY_VERSION: 25-x64
    #   USE_MSYS: true
    #   SUITES: "spec"
    #   BUNDLE_JOBS: 4
    - RUBY_VERSION: 24-x64
      USE_MSYS: true
      SUITES: "acceptance:local"
      BUNDLE_JOBS: 4
    - RUBY_VERSION: 24-x64
      USE_MSYS: true
      SUITES: "spec"
      BUNDLE_JOBS: 1
    - RUBY_VERSION: 23-x64
      USE_CYGWIN: true
      SUITES: "spec"
      BUNDLE_JOBS: 1
    - RUBY_VERSION: 21-x64
      USE_CYGWIN: true
      SUITES: "spec"
      BUNDLE_JOBS: 1

install:
  - ps: |
      if ($ENV:USE_MSYS -ne $Null) {
        Push-Location "C:\Ruby${ENV:RUBY_VERSION}\bin"
        .\ridk.ps1 install 2 3
        .\ridk.ps1 enable
        Pop-Location
      }
      ElseIf ($ENV:USE_CYGWIN) {
        $ENV:PATH = "C:\Ruby${ENV:RUBY_VERSION}\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;" + $ENV:PATH
      }
  - ps: |
      $CACertFile = Join-Path -Path $ENV:AppData -ChildPath "RubyCACert.pem"
      If (-Not (Test-Path -Path $CACertFile)) {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri "https://curl.haxx.se/ca/cacert.pem" -UseBasicParsing -OutFile $CACertFile | Out-Null
      }
      $ENV:SSL_CERT_FILE = $CACertFile
  - echo %PATH%
  - bundle install --retry 2 --without development

build: off

branches:
  only:
    - master

before_test:
  - bundle env
  - type Gemfile.lock

test_script:
  - bundle exec rake %SUITES%

# Uncomment this block to enable RDP access to the AppVeyor test instance for
# debugging purposes.
# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
  - provider: HipChat
    auth_token:
      secure: W9FwcoLtq+0XUqE3lM6m8zGdPdIOfHNafvdVD0qtoG0ra3C3hkseSaHR6uO8h/h2
    room: 3519749
    template: >
      {{repositoryName}}#{{buildNumber}} ({{#isPullRequest}}PR {{pullRequestId}}{{/isPullRequest}}{{^isPullRequest}}{{branch}}{{/isPullRequest}} - {{commitId}} : {{commitAuthor}}): {{status}} (<a href="{{buildUrl}}">Details</a>{{#isPullRequest}} | <a href="https://github.com/{{repositoryName}}/pull/{{pullRequestId}}">PR</a>{{/isPullRequest}})
